services:
  DEVPROJECT:
    container_name: DEVPROJECT
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - devcontainer_DEVPROJECT:/workspace
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    command: sleep infinity

volumes:
  devcontainer_DEVPROJECT:
    external: true